language: node_js
node_js:
- '8.4'
notifications:
  slack:
    secure: CWLnERWGXzdZNlPHy61V8B7+B0chWue5OFRYQFC6cnfnoaSNepbCcdmd+bYeDmJyQFS2yGAqDVyXc9ksTskojhhODcwUQRg3N9GHESUxW8LDRCc41faVdg4DcSZ7ikdH0FfRyVm0FoOZUQXm6aAD1gmgKmdRQVusAv/Vaa8JaJPbZVtviSp984m03w+2bIpAigPOI6PphEnh+V47JMnQQDRYObTnCzuHJwa5anPmoC7V94nvf/ZqkQn2FrIwPB97ji1qx2TZyTF7ncTFsZexFyTJdS9CJVoP6IMtbRtvkj23M+dDPr21Wue9kAwqo4RQTjZ0Y8zLxdh/Lokl0a6m47yL61Oo1+oDfpq8e+vIymTSO2GmVfdzd9VTZuZxypmYlKTAnqTDDsi+o1J+wy/GAumzRbylB3I7W6mMLHU+/RWxAa3sIo6pTazQwLOUvtWz/mGeVV+qqu7Sz/xjPvECbUBZd2ns1WuVIo9puIzChJfwuevLU07o6/FD/FDYSBD/XAPRhiB6BffLKQLFrGz0xOBELOsFvIf4UjN4WqWWTe4XrHwGMHoY/5jZQ8SbhWpFdFRVYkJrI5/YsZRF5DI3UtdKTx+Q7Cd8stiuKn8yEvSOly1u0H2pz1YHdQccfbQw4u4h839g+1zC5H2VqQQAQPXGEwd6ebGiAN2xLRgV4O0=
  on_success: never
  on_failure: always
